export type EconomicContext = "local" | "national" | "state" | "international";

export interface EconomicMetric {
  id: string;
  name: string;
  value: number;
  unit: string;
  change: number;
  changePercent: number;
  trend: "up" | "down" | "stable";
  period: string;
}

export interface EconomicNews {
  id: string;
  sn: number;
  headline: string;
  news: string;
  impact: "positive" | "negative" | "neutral";
  timestamp: Date;
  source: string;
  category: string;
}

export interface EconomicForecast {
  id: string;
  indicator: string;
  currentValue: number;
  forecastValue: number;
  confidence: number;
  timeframe: string;
  methodology: string;
}

// Mock data with all 20 specified economic sectors
export const economicMetrics: Record<EconomicContext, EconomicMetric[]> = {
  local: [
    {
      id: "1",
      name: "GDP Growth Rate",
      value: 3.2,
      unit: "%",
      change: 0.4,
      changePercent: 14.3,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "2",
      name: "Inflation Rate",
      value: 2.8,
      unit: "%",
      change: -0.2,
      changePercent: -6.7,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "3",
      name: "Unemployment Rate",
      value: 4.1,
      unit: "%",
      change: -0.3,
      changePercent: -6.8,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "4",
      name: "Interest Rates",
      value: 5.25,
      unit: "%",
      change: 0.0,
      changePercent: 0.0,
      trend: "stable",
      period: "Dec 2024",
    },
    {
      id: "5",
      name: "Exchange Rates",
      value: 1.05,
      unit: "USD/EUR",
      change: 0.02,
      changePercent: 1.9,
      trend: "up",
      period: "Dec 2024",
    },
    {
      id: "6",
      name: "Consumer Price Index",
      value: 307.4,
      unit: "Index",
      change: 1.2,
      changePercent: 0.4,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "7",
      name: "Producer Price Index",
      value: 132.8,
      unit: "Index",
      change: 0.8,
      changePercent: 0.6,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "8",
      name: "Industrial Production",
      value: 102.5,
      unit: "Index",
      change: 1.5,
      changePercent: 1.5,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "9",
      name: "Retail Sales",
      value: 685.2,
      unit: "$B",
      change: 12.4,
      changePercent: 1.8,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "10",
      name: "Consumer Confidence Index",
      value: 108.3,
      unit: "Index",
      change: 2.1,
      changePercent: 2.0,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "11",
      name: "Business Confidence Index",
      value: 95.7,
      unit: "Index",
      change: -1.2,
      changePercent: -1.2,
      trend: "down",
      period: "Q3 2024",
    },
    {
      id: "12",
      name: "Government Spending",
      value: 1.8,
      unit: "$T",
      change: 0.08,
      changePercent: 4.6,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "13",
      name: "Trade Balance",
      value: -67.4,
      unit: "$B",
      change: -2.1,
      changePercent: 3.2,
      trend: "down",
      period: "Oct 2024",
    },
    {
      id: "14",
      name: "Housing Market Trends",
      value: 1.33,
      unit: "M Units",
      change: 0.05,
      changePercent: 3.9,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "15",
      name: "Stock Market Performance",
      value: 35891,
      unit: "Points",
      change: 428,
      changePercent: 1.2,
      trend: "up",
      period: "Dec 12",
    },
    {
      id: "16",
      name: "Corporate Earnings Growth",
      value: 8.4,
      unit: "%",
      change: 1.2,
      changePercent: 16.7,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "17",
      name: "Labor Force Participation",
      value: 63.4,
      unit: "%",
      change: 0.1,
      changePercent: 0.2,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "18",
      name: "Wage Growth",
      value: 4.2,
      unit: "%",
      change: 0.3,
      changePercent: 7.7,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "19",
      name: "Commodity Prices",
      value: 71.8,
      unit: "$/Barrel",
      change: 2.3,
      changePercent: 3.3,
      trend: "up",
      period: "Dec 12",
    },
    {
      id: "20",
      name: "Money Supply Growth",
      value: 5.8,
      unit: "%",
      change: -0.4,
      changePercent: -6.5,
      trend: "down",
      period: "Q3 2024",
    },
  ],
  national: [
    {
      id: "1",
      name: "GDP Growth Rate",
      value: 2.8,
      unit: "%",
      change: 0.2,
      changePercent: 7.7,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "2",
      name: "Inflation Rate",
      value: 3.1,
      unit: "%",
      change: -0.1,
      changePercent: -3.1,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "3",
      name: "Unemployment Rate",
      value: 3.7,
      unit: "%",
      change: -0.1,
      changePercent: -2.6,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "4",
      name: "Interest Rates",
      value: 5.5,
      unit: "%",
      change: 0.0,
      changePercent: 0.0,
      trend: "stable",
      period: "Dec 2024",
    },
    {
      id: "5",
      name: "Exchange Rates",
      value: 1.0567,
      unit: "USD/EUR",
      change: 0.015,
      changePercent: 1.4,
      trend: "up",
      period: "Dec 2024",
    },
    {
      id: "6",
      name: "Consumer Price Index",
      value: 310.2,
      unit: "Index",
      change: 0.9,
      changePercent: 0.3,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "7",
      name: "Producer Price Index",
      value: 135.1,
      unit: "Index",
      change: 1.1,
      changePercent: 0.8,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "8",
      name: "Industrial Production",
      value: 103.8,
      unit: "Index",
      change: 0.9,
      changePercent: 0.9,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "9",
      name: "Retail Sales",
      value: 714.5,
      unit: "$B",
      change: 8.2,
      changePercent: 1.2,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "10",
      name: "Consumer Confidence Index",
      value: 111.7,
      unit: "Index",
      change: 3.4,
      changePercent: 3.1,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "11",
      name: "Business Confidence Index",
      value: 98.2,
      unit: "Index",
      change: 1.5,
      changePercent: 1.6,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "12",
      name: "Government Spending",
      value: 6.2,
      unit: "$T",
      change: 0.15,
      changePercent: 2.5,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "13",
      name: "Trade Balance",
      value: -73.1,
      unit: "$B",
      change: -3.8,
      changePercent: 5.5,
      trend: "down",
      period: "Oct 2024",
    },
    {
      id: "14",
      name: "Housing Market Trends",
      value: 1.42,
      unit: "M Units",
      change: 0.08,
      changePercent: 6.0,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "15",
      name: "Stock Market Performance",
      value: 36104,
      unit: "Points",
      change: 512,
      changePercent: 1.4,
      trend: "up",
      period: "Dec 12",
    },
    {
      id: "16",
      name: "Corporate Earnings Growth",
      value: 11.2,
      unit: "%",
      change: 2.1,
      changePercent: 23.1,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "17",
      name: "Labor Force Participation",
      value: 63.8,
      unit: "%",
      change: 0.2,
      changePercent: 0.3,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "18",
      name: "Wage Growth",
      value: 4.6,
      unit: "%",
      change: 0.4,
      changePercent: 9.5,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "19",
      name: "Commodity Prices",
      value: 73.2,
      unit: "$/Barrel",
      change: 1.8,
      changePercent: 2.5,
      trend: "up",
      period: "Dec 12",
    },
    {
      id: "20",
      name: "Money Supply Growth",
      value: 6.1,
      unit: "%",
      change: -0.2,
      changePercent: -3.2,
      trend: "down",
      period: "Q3 2024",
    },
  ],
  state: [
    {
      id: "1",
      name: "GDP Growth Rate",
      value: 3.5,
      unit: "%",
      change: 0.3,
      changePercent: 9.4,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "2",
      name: "Inflation Rate",
      value: 2.9,
      unit: "%",
      change: -0.3,
      changePercent: -9.4,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "3",
      name: "Unemployment Rate",
      value: 3.9,
      unit: "%",
      change: -0.2,
      changePercent: -4.9,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "4",
      name: "Interest Rates",
      value: 5.35,
      unit: "%",
      change: 0.1,
      changePercent: 1.9,
      trend: "up",
      period: "Dec 2024",
    },
    {
      id: "5",
      name: "Exchange Rates",
      value: 1.0523,
      unit: "USD/EUR",
      change: 0.008,
      changePercent: 0.8,
      trend: "up",
      period: "Dec 2024",
    },
    {
      id: "6",
      name: "Consumer Price Index",
      value: 309.1,
      unit: "Index",
      change: 1.0,
      changePercent: 0.3,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "7",
      name: "Producer Price Index",
      value: 134.2,
      unit: "Index",
      change: 0.7,
      changePercent: 0.5,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "8",
      name: "Industrial Production",
      value: 104.2,
      unit: "Index",
      change: 1.8,
      changePercent: 1.8,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "9",
      name: "Retail Sales",
      value: 698.3,
      unit: "$B",
      change: 15.1,
      changePercent: 2.2,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "10",
      name: "Consumer Confidence Index",
      value: 112.5,
      unit: "Index",
      change: 4.2,
      changePercent: 3.9,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "11",
      name: "Business Confidence Index",
      value: 102.1,
      unit: "Index",
      change: 3.8,
      changePercent: 3.9,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "12",
      name: "Government Spending",
      value: 84.2,
      unit: "$B",
      change: 3.1,
      changePercent: 3.8,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "13",
      name: "Trade Balance",
      value: 12.3,
      unit: "$B",
      change: 1.8,
      changePercent: 17.1,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "14",
      name: "Housing Market Trends",
      value: 0.18,
      unit: "M Units",
      change: 0.012,
      changePercent: 7.1,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "15",
      name: "Stock Market Performance",
      value: 2847,
      unit: "Points",
      change: 38,
      changePercent: 1.4,
      trend: "up",
      period: "Dec 12",
    },
    {
      id: "16",
      name: "Corporate Earnings Growth",
      value: 9.8,
      unit: "%",
      change: 1.6,
      changePercent: 19.5,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "17",
      name: "Labor Force Participation",
      value: 64.2,
      unit: "%",
      change: 0.3,
      changePercent: 0.5,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "18",
      name: "Wage Growth",
      value: 4.8,
      unit: "%",
      change: 0.5,
      changePercent: 11.6,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "19",
      name: "Commodity Prices",
      value: 69.5,
      unit: "$/Barrel",
      change: 1.2,
      changePercent: 1.8,
      trend: "up",
      period: "Dec 12",
    },
    {
      id: "20",
      name: "Money Supply Growth",
      value: 5.5,
      unit: "%",
      change: -0.1,
      changePercent: -1.8,
      trend: "down",
      period: "Q3 2024",
    },
  ],
  international: [
    {
      id: "1",
      name: "GDP Growth Rate",
      value: 3.0,
      unit: "%",
      change: -0.1,
      changePercent: -3.2,
      trend: "down",
      period: "Q3 2024",
    },
    {
      id: "2",
      name: "Inflation Rate",
      value: 5.2,
      unit: "%",
      change: 0.3,
      changePercent: 6.1,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "3",
      name: "Unemployment Rate",
      value: 6.8,
      unit: "%",
      change: 0.2,
      changePercent: 3.0,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "4",
      name: "Interest Rates",
      value: 3.75,
      unit: "%",
      change: -0.25,
      changePercent: -6.2,
      trend: "down",
      period: "Dec 2024",
    },
    {
      id: "5",
      name: "Exchange Rates",
      value: 0.9467,
      unit: "EUR/USD",
      change: -0.015,
      changePercent: -1.6,
      trend: "down",
      period: "Dec 2024",
    },
    {
      id: "6",
      name: "Consumer Price Index",
      value: 118.4,
      unit: "Index",
      change: 0.6,
      changePercent: 0.5,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "7",
      name: "Producer Price Index",
      value: 115.8,
      unit: "Index",
      change: 1.2,
      changePercent: 1.0,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "8",
      name: "Industrial Production",
      value: 98.2,
      unit: "Index",
      change: -0.8,
      changePercent: -0.8,
      trend: "down",
      period: "Oct 2024",
    },
    {
      id: "9",
      name: "Retail Sales",
      value: 412.7,
      unit: "€B",
      change: -2.1,
      changePercent: -0.5,
      trend: "down",
      period: "Oct 2024",
    },
    {
      id: "10",
      name: "Consumer Confidence Index",
      value: 96.3,
      unit: "Index",
      change: -1.4,
      changePercent: -1.4,
      trend: "down",
      period: "Nov 2024",
    },
    {
      id: "11",
      name: "Business Confidence Index",
      value: 89.7,
      unit: "Index",
      change: -2.1,
      changePercent: -2.3,
      trend: "down",
      period: "Q3 2024",
    },
    {
      id: "12",
      name: "Government Spending",
      value: 2.1,
      unit: "€T",
      change: 0.05,
      changePercent: 2.4,
      trend: "up",
      period: "Q3 2024",
    },
    {
      id: "13",
      name: "Trade Balance",
      value: 186.2,
      unit: "€B",
      change: 8.4,
      changePercent: 4.7,
      trend: "up",
      period: "Oct 2024",
    },
    {
      id: "14",
      name: "Housing Market Trends",
      value: 1.28,
      unit: "M Units",
      change: -0.04,
      changePercent: -3.0,
      trend: "down",
      period: "Oct 2024",
    },
    {
      id: "15",
      name: "Stock Market Performance",
      value: 4792,
      unit: "Points",
      change: -23,
      changePercent: -0.5,
      trend: "down",
      period: "Dec 12",
    },
    {
      id: "16",
      name: "Corporate Earnings Growth",
      value: 5.1,
      unit: "%",
      change: -1.2,
      changePercent: -19.0,
      trend: "down",
      period: "Q3 2024",
    },
    {
      id: "17",
      name: "Labor Force Participation",
      value: 72.8,
      unit: "%",
      change: 0.1,
      changePercent: 0.1,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "18",
      name: "Wage Growth",
      value: 3.8,
      unit: "%",
      change: 0.2,
      changePercent: 5.6,
      trend: "up",
      period: "Nov 2024",
    },
    {
      id: "19",
      name: "Commodity Prices",
      value: 67.9,
      unit: "$/Barrel",
      change: -1.8,
      changePercent: -2.6,
      trend: "down",
      period: "Dec 12",
    },
    {
      id: "20",
      name: "Money Supply Growth",
      value: 4.2,
      unit: "%",
      change: -0.8,
      changePercent: -16.0,
      trend: "down",
      period: "Q3 2024",
    },
  ],
};

export const economicNews: Record<EconomicContext, EconomicNews[]> = {
  local: [
    {
      id: "1",
      sn: 1,
      headline: "Local Tech Sector Shows Strong Q3 Growth",
      news: "The city's technology sector expanded by 8.2% in the third quarter, driven by AI startups and software development firms.",
      impact: "positive",
      timestamp: new Date("2024-12-10T09:30:00"),
      source: "City Economic Development",
      category: "Technology",
    },
    {
      id: "2",
      sn: 2,
      headline: "New Manufacturing Plant Opens Downtown",
      news: "A $45M electric vehicle component manufacturing facility begins operations, creating 380 new jobs.",
      impact: "positive",
      timestamp: new Date("2024-12-10T11:15:00"),
      source: "Local Business Journal",
      category: "Manufacturing",
    },
    {
      id: "3",
      sn: 3,
      headline: "Housing Prices Rise 3.2% in Q3",
      news: "Local real estate market continues upward trend with median home price reaching $385,000.",
      impact: "neutral",
      timestamp: new Date("2024-12-09T16:20:00"),
      source: "Real Estate Board",
      category: "Housing",
    },
    {
      id: "4",
      sn: 4,
      headline: "Small Business Support Program Launched",
      news: "City council approves $2.5M fund to support local entrepreneurs and small business expansion.",
      impact: "positive",
      timestamp: new Date("2024-12-09T14:45:00"),
      source: "City Council",
      category: "Small Business",
    },
    {
      id: "5",
      sn: 5,
      headline: "Infrastructure Investment Boosts Construction",
      news: "Road improvement projects and bridge repairs drive 12% increase in local construction activity.",
      impact: "positive",
      timestamp: new Date("2024-12-08T10:30:00"),
      source: "Department of Public Works",
      category: "Infrastructure",
    },
    {
      id: "6",
      sn: 6,
      headline: "Local Unemployment Drops to 3.8%",
      news: "Job market strengthens as 1,200 new positions were added across multiple sectors last month.",
      impact: "positive",
      timestamp: new Date("2024-12-08T08:00:00"),
      source: "Labor Department",
      category: "Employment",
    },
    {
      id: "7",
      sn: 7,
      headline: "Energy Costs Increase 5% for Businesses",
      news: "Commercial electricity rates rise due to increased demand and infrastructure upgrades.",
      impact: "negative",
      timestamp: new Date("2024-12-07T13:30:00"),
      source: "Utility Company",
      category: "Energy",
    },
    {
      id: "8",
      sn: 8,
      headline: "Local Tourism Revenue Up 15%",
      news: "Visitor spending reaches $128M in Q3, surpassing pre-pandemic levels by significant margin.",
      impact: "positive",
      timestamp: new Date("2024-12-07T09:45:00"),
      source: "Tourism Board",
      category: "Tourism",
    },
    {
      id: "9",
      sn: 9,
      headline: "New Business Permits Hit 5-Year High",
      news: "Entrepreneurial activity surges with 156 new business licenses issued in November alone.",
      impact: "positive",
      timestamp: new Date("2024-12-06T15:20:00"),
      source: "Business Licensing",
      category: "Business Formation",
    },
    {
      id: "10",
      sn: 10,
      headline: "Local Bank Expands Lending Programs",
      news: "Community bank announces $25M increase in small business loan availability with reduced rates.",
      impact: "positive",
      timestamp: new Date("2024-12-06T12:10:00"),
      source: "Community Bank",
      category: "Finance",
    },
  ],
  national: [
    {
      id: "1",
      sn: 1,
      headline: "Federal Reserve Maintains Interest Rates",
      news: "The Federal Reserve decided to keep interest rates unchanged at 5.25-5.50% following December FOMC meeting.",
      impact: "neutral",
      timestamp: new Date("2024-12-11T14:00:00"),
      source: "Federal Reserve",
      category: "Monetary Policy",
    },
    {
      id: "2",
      sn: 2,
      headline: "GDP Growth Exceeds Expectations at 2.8%",
      news: "Third quarter economic growth outpaces forecasts, driven by consumer spending and business investment.",
      impact: "positive",
      timestamp: new Date("2024-12-11T09:30:00"),
      source: "Bureau of Economic Analysis",
      category: "Economic Growth",
    },
    {
      id: "3",
      sn: 3,
      headline: "Inflation Rate Moderates to 3.1%",
      news: "Consumer price index shows continued cooling from peak levels, approaching Fed's 2% target.",
      impact: "positive",
      timestamp: new Date("2024-12-10T08:30:00"),
      source: "Bureau of Labor Statistics",
      category: "Inflation",
    },
    {
      id: "4",
      sn: 4,
      headline: "Job Market Remains Robust",
      news: "Unemployment rate holds steady at 3.7% with 199,000 new jobs added in November.",
      impact: "positive",
      timestamp: new Date("2024-12-10T10:15:00"),
      source: "Department of Labor",
      category: "Employment",
    },
    {
      id: "5",
      sn: 5,
      headline: "Consumer Spending Drives Holiday Season",
      news: "Retail sales surge 4.2% in November as holiday shopping begins earlier than previous years.",
      impact: "positive",
      timestamp: new Date("2024-12-09T11:45:00"),
      source: "Commerce Department",
      category: "Consumer Spending",
    },
    {
      id: "6",
      sn: 6,
      headline: "Manufacturing Sector Shows Resilience",
      news: "Industrial production increases 0.9% as automotive and technology sectors lead growth.",
      impact: "positive",
      timestamp: new Date("2024-12-09T14:20:00"),
      source: "Federal Reserve",
      category: "Manufacturing",
    },
    {
      id: "7",
      sn: 7,
      headline: "Trade Deficit Narrows Unexpectedly",
      news: "October trade gap decreases to $73.1B as exports rise faster than imports for second consecutive month.",
      impact: "positive",
      timestamp: new Date("2024-12-08T13:00:00"),
      source: "Census Bureau",
      category: "Trade",
    },
    {
      id: "8",
      sn: 8,
      headline: "Housing Market Shows Mixed Signals",
      news: "Home sales increase 6% while construction permits decline 3.2% amid affordability concerns.",
      impact: "neutral",
      timestamp: new Date("2024-12-08T15:30:00"),
      source: "National Association of Realtors",
      category: "Housing",
    },
    {
      id: "9",
      sn: 9,
      headline: "Corporate Earnings Beat Estimates",
      news: "S&P 500 companies report 11.2% earnings growth in Q3, exceeding analyst projections significantly.",
      impact: "positive",
      timestamp: new Date("2024-12-07T16:45:00"),
      source: "FactSet",
      category: "Corporate Earnings",
    },
    {
      id: "10",
      sn: 10,
      headline: "Energy Independence Reaches New Milestone",
      news: "US crude oil production hits record high of 13.2 million barrels per day in November.",
      impact: "positive",
      timestamp: new Date("2024-12-07T12:20:00"),
      source: "Energy Information Administration",
      category: "Energy",
    },
  ],
  state: [
    {
      id: "1",
      sn: 1,
      headline: "State Budget Surplus Reaches Record High",
      news: "State treasury reports a $2.4B budget surplus for fiscal year 2024, enabling new infrastructure investments.",
      impact: "positive",
      timestamp: new Date("2024-12-11T11:30:00"),
      source: "State Treasury",
      category: "Public Finance",
    },
    {
      id: "2",
      sn: 2,
      headline: "Major Tech Company Announces State Expansion",
      news: "Global software firm plans $800M data center investment, creating 2,500 high-paying jobs over three years.",
      impact: "positive",
      timestamp: new Date("2024-12-10T13:45:00"),
      source: "Economic Development Authority",
      category: "Technology Investment",
    },
    {
      id: "3",
      sn: 3,
      headline: "State Unemployment Falls to 3.9%",
      news: "Job market strengthens across all regions with particularly strong growth in healthcare and professional services.",
      impact: "positive",
      timestamp: new Date("2024-12-10T08:15:00"),
      source: "State Labor Department",
      category: "Employment",
    },
    {
      id: "4",
      sn: 4,
      headline: "Green Energy Initiative Gains Momentum",
      news: "State approves $1.2B in renewable energy projects, aiming for 50% clean electricity by 2030.",
      impact: "positive",
      timestamp: new Date("2024-12-09T10:30:00"),
      source: "Public Utilities Commission",
      category: "Energy Policy",
    },
    {
      id: "5",
      sn: 5,
      headline: "Education Funding Receives Major Boost",
      news: "Legislature allocates additional $450M for K-12 education, including teacher pay raises and facility upgrades.",
      impact: "positive",
      timestamp: new Date("2024-12-09T14:50:00"),
      source: "Department of Education",
      category: "Education",
    },
    {
      id: "6",
      sn: 6,
      headline: "Agricultural Exports Hit All-Time High",
      news: "State farmers benefit from strong international demand, with agricultural exports reaching $8.7B in 2024.",
      impact: "positive",
      timestamp: new Date("2024-12-08T09:20:00"),
      source: "Department of Agriculture",
      category: "Agriculture",
    },
    {
      id: "7",
      sn: 7,
      headline: "Infrastructure Bill Passes State Senate",
      news: "Bipartisan support secures $3.1B infrastructure package focusing on roads, bridges, and broadband expansion.",
      impact: "positive",
      timestamp: new Date("2024-12-08T16:40:00"),
      source: "State Senate",
      category: "Infrastructure",
    },
    {
      id: "8",
      sn: 8,
      headline: "Population Growth Drives Housing Demand",
      news: "State population increases 1.8% annually, leading to highest housing construction levels since 2007.",
      impact: "neutral",
      timestamp: new Date("2024-12-07T11:10:00"),
      source: "Housing Authority",
      category: "Demographics",
    },
    {
      id: "9",
      sn: 9,
      headline: "State Credit Rating Upgraded",
      news: "Moody's raises state's credit rating to AA+ citing strong fiscal management and economic diversification.",
      impact: "positive",
      timestamp: new Date("2024-12-07T15:25:00"),
      source: "Moody's Investors Service",
      category: "Credit Rating",
    },
    {
      id: "10",
      sn: 10,
      headline: "Tourism Industry Breaks Revenue Records",
      news: "Visitor spending reaches $24.8B in 2024, surpassing pre-pandemic levels and supporting 285,000 jobs.",
      impact: "positive",
      timestamp: new Date("2024-12-06T13:55:00"),
      source: "Tourism Commission",
      category: "Tourism",
    },
  ],
  international: [
    {
      id: "1",
      sn: 1,
      headline: "ECB Cuts Interest Rates by 0.25%",
      news: "European Central Bank reduces key interest rate to 3.75% amid slowing eurozone growth and easing inflation.",
      impact: "neutral",
      timestamp: new Date("2024-12-12T13:45:00"),
      source: "European Central Bank",
      category: "Monetary Policy",
    },
    {
      id: "2",
      sn: 2,
      headline: "China's GDP Growth Slows to 4.8%",
      news: "Chinese economy faces headwinds from property sector weakness and reduced consumer confidence in Q3.",
      impact: "negative",
      timestamp: new Date("2024-12-11T06:30:00"),
      source: "National Bureau of Statistics China",
      category: "Economic Growth",
    },
    {
      id: "3",
      sn: 3,
      headline: "UK Inflation Rises to 4.6%",
      news: "British inflation accelerates above Bank of England's target, raising concerns about persistent price pressures.",
      impact: "negative",
      timestamp: new Date("2024-12-11T09:00:00"),
      source: "Office for National Statistics UK",
      category: "Inflation",
    },
    {
      id: "4",
      sn: 4,
      headline: "Japan's Yen Weakens to 150 vs Dollar",
      news: "Japanese currency continues decline amid monetary policy divergence with major central banks.",
      impact: "negative",
      timestamp: new Date("2024-12-10T23:30:00"),
      source: "Bank of Japan",
      category: "Currency",
    },
    {
      id: "5",
      sn: 5,
      headline: "Global Trade Volume Contracts 1.2%",
      news: "World trade organization reports decline in international commerce amid geopolitical tensions and supply chain disruptions.",
      impact: "negative",
      timestamp: new Date("2024-12-10T12:15:00"),
      source: "World Trade Organization",
      category: "Global Trade",
    },
    {
      id: "6",
      sn: 6,
      headline: "Oil Prices Stabilize Near $68/Barrel",
      news: "Crude oil markets find equilibrium after OPEC+ production adjustments and seasonal demand patterns.",
      impact: "neutral",
      timestamp: new Date("2024-12-09T18:45:00"),
      source: "International Energy Agency",
      category: "Energy Markets",
    },
    {
      id: "7",
      sn: 7,
      headline: "European Manufacturing PMI Falls Below 50",
      news: "Eurozone manufacturing activity contracts for fourth consecutive month as demand weakens across key sectors.",
      impact: "negative",
      timestamp: new Date("2024-12-09T10:00:00"),
      source: "IHS Markit",
      category: "Manufacturing",
    },
    {
      id: "8",
      sn: 8,
      headline: "Emerging Markets Face Capital Outflows",
      news: "Developing economies experience $18B in portfolio outflows as investors seek safety in developed markets.",
      impact: "negative",
      timestamp: new Date("2024-12-08T14:20:00"),
      source: "Institute of International Finance",
      category: "Capital Flows",
    },
    {
      id: "9",
      sn: 9,
      headline: "Global Food Prices Rise 2.8%",
      news: "UN Food and Agriculture Organization reports increase driven by wheat and vegetable oil price volatility.",
      impact: "negative",
      timestamp: new Date("2024-12-08T11:30:00"),
      source: "FAO",
      category: "Commodity Prices",
    },
    {
      id: "10",
      sn: 10,
      headline: "IMF Revises Global Growth Forecast Down",
      news: "International Monetary Fund lowers 2025 global GDP growth projection to 2.8% citing multiple economic headwinds.",
      impact: "negative",
      timestamp: new Date("2024-12-07T17:00:00"),
      source: "International Monetary Fund",
      category: "Global Outlook",
    },
  ],
};

export const economicForecasts: Record<EconomicContext, EconomicForecast[]> = {
  local: [
    {
      id: "1",
      indicator: "Local GDP Growth",
      currentValue: 3.2,
      forecastValue: 3.8,
      confidence: 75,
      timeframe: "Q1 2025",
      methodology: "Regression Analysis",
    },
  ],
  national: [
    {
      id: "1",
      indicator: "GDP Growth Rate",
      currentValue: 2.8,
      forecastValue: 2.4,
      confidence: 72,
      timeframe: "Q1 2025",
      methodology: "Econometric Model",
    },
  ],
  state: [
    {
      id: "1",
      indicator: "State GDP Growth",
      currentValue: 3.5,
      forecastValue: 3.1,
      confidence: 69,
      timeframe: "Q1 2025",
      methodology: "State-level VAR Model",
    },
  ],
  international: [
    {
      id: "1",
      indicator: "Global GDP Growth",
      currentValue: 3.0,
      forecastValue: 2.8,
      confidence: 65,
      timeframe: "Q1 2025",
      methodology: "Global VAR Model",
    },
  ],
};
