# Generated by Django 4.2.28 on 2026-03-02 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_workers', models.IntegerField(default=1)),
                ('sector', models.CharField(max_length=100)),
                ('company_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('enterprise', 'Enterprise')], default='small', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('fiscal_year_end_date', models.DateField(blank=True, null=True)),
                ('currency_format', models.CharField(blank=True, max_length=50)),
                ('currency_preference', models.CharField(blank=True, max_length=10)),
                ('logo', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=20)),
                ('number_of_entities', models.IntegerField(default=1)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
