# Generated by Django 4.2.28 on 2026-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_disruptionrisk_inventorylocation_inventoryvaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='demand_assumption',
            field=models.FloatField(default=0, help_text='Demand assumption for segment'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='growth_rate',
            field=models.FloatField(default=0, help_text='Growth rate percentage'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='retention',
            field=models.FloatField(default=0, help_text='Retention rate percentage'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='seasonality',
            field=models.FloatField(default=0, help_text='Seasonality factor'),
        ),
        migrations.AddField(
            model_name='revenueprojection',
            name='actual_to_date',
            field=models.FloatField(default=0, help_text='Actual revenue to date'),
        ),
        migrations.AddField(
            model_name='revenueprojection',
            name='conservative',
            field=models.FloatField(default=0, help_text='Conservative revenue projection'),
        ),
        migrations.AddField(
            model_name='revenueprojection',
            name='optimistic',
            field=models.FloatField(default=0, help_text='Optimistic revenue projection'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='segment',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('enterprise', 'Enterprise'), ('smb', 'SMB'), ('startup', 'Startup')], max_length=20),
        ),
    ]
