# Generated by Django 4.2.29 on 2026-03-12 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_customerprofile_demand_assumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowforecast',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_forecasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coststructure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueprojection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_projections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioplanning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_plannings', to=settings.AUTH_USER_MODEL),
        ),
    ]
