# Generated by Django 4.2.29 on 2026-03-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_cashflowforecast_user_coststructure_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrecord',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='period',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='assignee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='completion_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='findings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom')], default='quarterly', max_length=20),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='effective_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='entity',
            field=models.CharField(default='', help_text='Company or entity name', max_length=200),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='estimated_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='marginal_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='tax_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='taxable_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('filed', 'Filed'), ('amended', 'Amended')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TaxRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('deduction', 'Deduction'), ('credit', 'Credit'), ('timing', 'Timing'), ('structure', 'Structure'), ('investment', 'Investment')], default='deduction', max_length=20)),
                ('potential_savings', models.FloatField(default=0)),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('requirements', models.JSONField(default=list)),
                ('implemented', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPlanningScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('current_tax', models.FloatField(default=0)),
                ('projected_tax', models.FloatField(default=0)),
                ('savings', models.FloatField(default=0)),
                ('timeframe', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('steps', models.JSONField(default=list)),
                ('confidence', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_planning_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], default='success', max_length=20)),
                ('category', models.CharField(choices=[('calculation', 'Calculation'), ('filing', 'Filing'), ('document', 'Document'), ('planning', 'Planning'), ('compliance', 'Compliance')], default='calculation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('regulation', 'Regulation'), ('form', 'Form'), ('deadline', 'Deadline'), ('rate_change', 'Rate Change'), ('guidance', 'Guidance')], default='regulation', max_length=20)),
                ('jurisdiction', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('local', 'Local')], default='federal', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('implemented', 'Implemented'), ('archived', 'Archived')], default='new', max_length=20)),
                ('action_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('event_based', 'Event-Based')], default='monthly', max_length=20)),
                ('agency', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(max_length=200)),
                ('consequence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('consequence_detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('at_risk', 'At Risk'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('dependencies', models.JSONField(default=list)),
                ('documentation_required', models.JSONField(default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
