# Generated by Django 4.2.29 on 2026-03-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_revenuetarget_keyrisk_keyassumption_growthtrajectory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Revenue', 'Revenue'), ('Expenses', 'Expenses'), ('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity')], max_length=30)),
                ('item', models.CharField(max_length=200)),
                ('current_amount', models.FloatField(default=0)),
                ('budget_amount', models.FloatField(default=0)),
                ('last_year_amount', models.FloatField(default=0)),
                ('unit', models.CharField(default='USD', max_length=20)),
                ('period', models.CharField(default='annual', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_line_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'item'],
            },
        ),
    ]
