# Generated by Django 4.2.29 on 2026-03-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_financiallineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Financial', 'Financial'), ('Customer', 'Customer'), ('Sales & Marketing', 'Sales & Marketing'), ('Operational', 'Operational'), ('HR & Employee', 'HR & Employee'), ('Project & Product', 'Project & Product'), ('Innovation & Growth', 'Innovation & Growth'), ('Digital & IT', 'Digital & IT')], max_length=50)),
                ('metric', models.CharField(max_length=200)),
                ('current', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('last_month', models.CharField(blank=True, max_length=50)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('change', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('excellent', 'Excellent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'metric'],
            },
        ),
    ]
