# Generated by Django 4.2.29 on 2026-03-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_businessmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSegmentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=120)),
                ('revenue', models.FloatField(default=0)),
                ('percentage_of_total', models.FloatField(default=0)),
                ('growth_rate', models.FloatField(default=0)),
                ('customer_count', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_segment_breakdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'segment'],
            },
        ),
        migrations.CreateModel(
            name='RevenueScenarioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=100)),
                ('probability', models.IntegerField(default=0)),
                ('annual_revenue', models.FloatField(default=0)),
                ('operating_costs', models.FloatField(default=0)),
                ('net_profit', models.FloatField(default=0)),
                ('key_assumptions', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_scenario_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'scenario'],
            },
        ),
        migrations.CreateModel(
            name='RevenueRegionalForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('projected_revenue', models.FloatField(default=0)),
                ('revenue_share', models.FloatField(default=0, help_text='Region share of total revenue percentage')),
                ('growth_rate', models.FloatField(default=0, help_text='Growth rate percentage')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_regional_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'region'],
            },
        ),
        migrations.CreateModel(
            name='RevenueProductServiceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('projection_year', models.IntegerField(default=2025)),
                ('projected_revenue', models.FloatField(default=0)),
                ('growth_rate', models.FloatField(default=0, help_text='Growth rate percentage')),
                ('market_share', models.FloatField(default=0, help_text='Market share percentage')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_product_service_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RevenueHistoricalComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('total_revenue', models.FloatField(default=0)),
                ('growth_percent', models.FloatField(default=0)),
                ('growth_label', models.CharField(default='YoY Growth', max_length=120)),
                ('supporting_metric_label', models.CharField(default='Confidence Level', max_length=120)),
                ('supporting_metric_value', models.CharField(default='0%', max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_historical_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RevenueForecastMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('projected_revenue', models.FloatField(default=0)),
                ('metric_label', models.CharField(default='Model Accuracy', max_length=120)),
                ('metric_value', models.CharField(default='0%', max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_forecast_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
