# Generated by Django 4.2.29 on 2026-03-20 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_revenuesegmentbreakdown_revenuescenariosnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('total_amount', models.FloatField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.FloatField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.operationalexpensecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_expense_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostTrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('benchmark', models.CharField(blank=True, default='', max_length=200)),
                ('bullet_points', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_trend_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CostOverviewMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=20)),
                ('description', models.TextField()),
                ('annual_total', models.FloatField(default=0)),
                ('monthly_average', models.FloatField(default=0)),
                ('percent_of_revenue', models.FloatField(default=0)),
                ('insight', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_overview_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'cost_type'],
            },
        ),
        migrations.CreateModel(
            name='CostMonthlyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('budget_amount', models.FloatField(default=0)),
                ('forecast_amount', models.FloatField(default=0)),
                ('actual_amount', models.FloatField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_monthly_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'month'],
            },
        ),
        migrations.CreateModel(
            name='CostBudgetScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.FloatField(default=0)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_budget_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
