# Generated by Django 4.2.29 on 2026-03-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_operationalexpensecategory_operationalexpenseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuetarget',
            name='q1_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenuetarget',
            name='q2_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenuetarget',
            name='q3_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenuetarget',
            name='q4_revenue',
            field=models.FloatField(default=0),
        ),
    ]
