# Generated by Django 4.2.29 on 2026-03-20 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_revenuetarget_q1_revenue_revenuetarget_q2_revenue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewProfitLossSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_profit', models.FloatField(default=0)),
                ('gross_margin', models.FloatField(default=0)),
                ('operating_expense', models.FloatField(default=0)),
                ('net_profit', models.FloatField(default=0)),
                ('net_margin', models.FloatField(default=0)),
                ('period_label', models.CharField(default='Current', max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overview_profit_loss_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OverviewKpiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_tracked', models.IntegerField(default=0)),
                ('excellent_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('fair_count', models.IntegerField(default=0)),
                ('needs_attention_count', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overview_kpi_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OverviewAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('warning', 'Warning'), ('danger', 'Danger'), ('info', 'Info'), ('success', 'Success')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overview_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
