# Generated by Django 4.2.29 on 2026-03-20 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_revenueoverviewupsellopportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueoverviewupsellopportunity',
            name='current_mrr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenueoverviewupsellopportunity',
            name='time_to_upgrade_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenueoverviewupsellopportunity',
            name='triggers',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='RevenueUpsellInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('high-priority', 'High-Priority Actions'), ('success-factor', 'Success Factors')], max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_upsell_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
