# Generated by Django 4.2.29 on 2026-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_revenueoverviewupsellopportunity_current_mrr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('advantage_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('brand', 'Brand'), ('price', 'Price'), ('distribution', 'Distribution'), ('technology', 'Technology'), ('team', 'Team'), ('other', 'Other')], max_length=50)),
                ('strength_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('sustainability', models.IntegerField(default=50, help_text='Sustainability score 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-strength_level', '-sustainability'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('market_size', models.FloatField(help_text='Segment size in millions')),
                ('percentage_of_total', models.FloatField(default=0, help_text='Percentage of total market')),
                ('avg_spending', models.FloatField(help_text='Average spending per customer')),
                ('growth_rate', models.FloatField(help_text='Segment growth rate percentage')),
                ('characteristics', models.JSONField(default=list, help_text='Key segment characteristics')),
                ('region', models.CharField(default='Global', max_length=100)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-growth_rate'],
            },
        ),
        migrations.CreateModel(
            name='IndustryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('trend', 'Trend'), ('threat', 'Threat'), ('opportunity', 'Opportunity'), ('observation', 'Observation')], default='observation', max_length=50)),
                ('impact_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('sources', models.JSONField(default=list, help_text='Reference sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('timeline', models.CharField(help_text='e.g., Q1 2025', max_length=100)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketNextStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_segment', models.CharField(max_length=200)),
                ('our_position', models.CharField(help_text='Our current market position', max_length=200)),
                ('market_leader', models.CharField(blank=True, max_length=200)),
                ('primary_competitors', models.JSONField(default=list, help_text='List of primary competitors')),
                ('market_share_estimate', models.FloatField(help_text='Our estimated market share percentage')),
                ('positioning_statement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('implementation_timeline', models.CharField(blank=True, max_length=200)),
                ('expected_impact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tam', models.FloatField(help_text='Total Addressable Market (in millions)')),
                ('sam', models.FloatField(help_text='Serviceable Addressable Market (in millions)')),
                ('som', models.FloatField(help_text='Serviceable Obtainable Market (in millions)')),
                ('growth_rate', models.FloatField(default=0, help_text='Market growth rate percentage')),
                ('timeframe', models.CharField(default='2025', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('region', models.CharField(default='Global', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Market Analysis Summary', max_length=300)),
                ('content', models.TextField(help_text='Full market summary text')),
                ('key_points', models.JSONField(default=list, help_text='Key summary points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('competitor_products', models.JSONField(default=list, help_text='List of competitor products to compare')),
                ('features', models.JSONField(default=dict, help_text='Feature comparison matrix')),
                ('pricing_comparison', models.JSONField(default=dict, help_text='Pricing data')),
                ('market_position', models.CharField(choices=[('premium', 'Premium'), ('aligned', 'Market Aligned'), ('competitive', 'Competitive'), ('discount', 'Discount')], default='aligned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('overview', 'Overview'), ('market', 'Market Analysis'), ('competitive', 'Competitive Analysis'), ('strategy', 'Strategy'), ('recommendation', 'Recommendation'), ('other', 'Other')], default='other', max_length=100)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-importance', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=200)),
                ('strengths', models.JSONField(default=list, help_text='List of strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of weaknesses')),
                ('opportunities', models.JSONField(default=list, help_text='List of opportunities')),
                ('threats', models.JSONField(default=list, help_text='List of threats')),
                ('overall_score', models.IntegerField(default=50, help_text='Overall SWOT score 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
    ]
