# Generated by Django 4.2.29 on 2026-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_competitiveadvantage_customersegmentdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., Q1 2025, 2026', max_length=50)),
                ('forecasted_demand', models.FloatField()),
                ('confidence_level', models.IntegerField(default=70, help_text='Confidence percentage')),
                ('assumptions', models.TextField(blank=True)),
                ('seasonality_factor', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketStrategyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('strategy_type', models.CharField(choices=[('pricing', 'Pricing'), ('positioning', 'Positioning'), ('product', 'Product'), ('marketing', 'Marketing'), ('partnership', 'Partnership'), ('expansion', 'Market Expansion'), ('defense', 'Competitive Defense'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True, help_text='Why this strategy is recommended')),
                ('expected_outcomes', models.JSONField(default=list, help_text='Expected outcomes')),
                ('implementation_steps', models.JSONField(default=list, help_text='Implementation steps')),
                ('success_metrics', models.JSONField(default=list, help_text='KPIs to track success')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
