# Generated by Django 4.2.29 on 2026-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_report_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elasticity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('elasticity_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('elasticity_period', models.CharField(default='Q3 2024', max_length=50)),
                ('competitive_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('competitive_change', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('competitive_period', models.CharField(default='This quarter', max_length=50)),
                ('acceptance_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('acceptance_change', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('acceptance_period', models.CharField(default='Last 7 days', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strategy_type', models.CharField(choices=[('value-based', 'Value Based'), ('tiered', 'Tiered'), ('dynamic', 'Dynamic'), ('cost-plus', 'Cost Plus'), ('penetration', 'Penetration')], max_length=50)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('a-b', 'A/B Test'), ('multivariate', 'Multivariate'), ('split', 'Split Test'), ('sequential', 'Sequential')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('variant_count', models.IntegerField(default=2)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
