# Generated by Django 4.2.29 on 2026-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_pricing_items_and_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingstrategy',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricingstrategy',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pricingstrategy',
            name='margin',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingstrategy',
            name='market_share',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('value-based', 'Value Based'), ('tiered', 'Tiered'), ('dynamic', 'Dynamic'), ('cost-plus', 'Cost Plus'), ('penetration', 'Penetration'), ('discrimination', 'Price Discrimination')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingstrategy',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
