# Generated by Django 4.2.29 on 2026-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_pricingstrategy_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='competitor',
            name='feature_highlights',
            field=models.JSONField(default=list, help_text='Competitive highlights'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='market_position',
            field=models.CharField(choices=[('premium', 'Premium'), ('mid-market', 'Mid Market'), ('budget', 'Budget')], default='mid-market', max_length=20),
        ),
        migrations.AddField(
            model_name='competitor',
            name='pricing_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competitor',
            name='pricing_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
