# Generated by Django 4.2.29 on 2026-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_budget_validation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedStressTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('alert-triangle', 'Alert Triangle'), ('trending-down', 'Trending Down'), ('activity', 'Activity')], default='alert-triangle', max_length=30)),
                ('scenario_template', models.JSONField(default=dict, help_text='Template used to run this recommendation as a scenario test.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioResilienceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=60)),
                ('value_tone', models.CharField(default='neutral', max_length=20)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
    ]
