# Generated by Django 4.2.29 on 2026-03-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_recommendedstresstest_scenarioresiliencemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioSummaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('total_scenarios', 'Total Scenarios'), ('critical_scenarios', 'Critical Scenarios'), ('average_probability', 'Average Probability'), ('resilience_score', 'Resilience Score')], max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
