# Generated by Django 4.2.29 on 2026-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_scenariosummarycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategoryDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('liquidity', 'Liquidity'), ('credit', 'Credit'), ('market', 'Market'), ('operational', 'Operational'), ('regulatory', 'Regulatory')], max_length=30, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=200)),
                ('risk_score', models.IntegerField(default=0)),
                ('recommended_actions', models.JSONField(default=list)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RiskSummaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('total_risks', 'Total Risks'), ('high_risk_items', 'High Risk Items'), ('average_risk_score', 'Avg Risk Score'), ('resolved_risks', 'Resolved Risks')], max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
