# Generated by Django 4.2.29 on 2026-03-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_riskcategorydistribution_riskmitigationstrategy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskCategoryDistribution',
        ),
        migrations.DeleteModel(
            name='RiskMitigationStrategy',
        ),
        migrations.DeleteModel(
            name='RiskSummaryCard',
        ),
        migrations.DeleteModel(
            name='ScenarioSummaryCard',
        ),
    ]
