# Generated by Django 4.2.29 on 2026-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_riskcategorydistribution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisoryinsight',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='advisoryinsight',
            name='confidence_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='advisoryinsight',
            name='financial_impact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='advisoryinsight',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='advisoryinsight',
            name='timeframe',
            field=models.CharField(default='90 days', max_length=50),
        ),
        migrations.AddField(
            model_name='advisoryinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advisoryinsight',
            name='category',
            field=models.CharField(choices=[('cost_optimization', 'Cost Optimization'), ('revenue_growth', 'Revenue Growth'), ('risk_management', 'Risk Management'), ('operational', 'Operational'), ('investment', 'Investment')], max_length=30),
        ),
    ]
