# Generated by Django 4.2.29 on 2026-03-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_advisoryinsight_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='category',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('cost', 'Cost'), ('efficiency', 'Efficiency'), ('growth', 'Growth'), ('financial', 'Financial'), ('operational', 'Operational'), ('sales', 'Sales'), ('productivity', 'Productivity'), ('risk', 'Risk')], default='financial', max_length=30),
        ),
        migrations.AddField(
            model_name='kpi',
            name='critical_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('upload', 'Upload'), ('auto_sync', 'Auto Sync')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='driver_link',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kpi',
            name='driver_type',
            field=models.CharField(choices=[('leading', 'Leading'), ('lagging', 'Lagging')], default='leading', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='impact',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kpi_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kpi',
            name='linked_budget_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kpi',
            name='trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='unit_of_measure',
            field=models.CharField(choices=[('%', 'Percentage'), ('$', 'Currency'), ('ratio', 'Ratio'), ('count', 'Count'), ('days', 'Days'), ('hours', 'Hours'), ('score', 'Score')], default='%', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='warning_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('critical', 'Critical'), ('exceeding_target', 'Exceeding Target'), ('off_track', 'Off Track')], default='on_track', max_length=20),
        ),
    ]
