# Generated by Django 4.2.29 on 2026-03-21 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_advicehubmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(db_index=True, max_length=100)),
                ('module_name', models.CharField(max_length=200)),
                ('module_icon', models.CharField(default='💡', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advice_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advice Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdviceHubMessage',
        ),
    ]
