import { EconomicContext } from "./economic-data";

export interface EconomicEvent {
  id: string;
  title: string;
  description: string;
  date: Date;
  time?: string;
  importance: "high" | "medium" | "low";
  category: string;
  impact: "bullish" | "bearish" | "neutral";
  source: string;
  previous?: string;
  forecast?: string;
  actual?: string;
}

export const upcomingEconomicEvents: Record<EconomicContext, EconomicEvent[]> =
  {
    local: [
      {
        id: "1",
        title: "City Council Budget Meeting",
        description:
          "Quarterly budget review and infrastructure spending approval for Q1 2025",
        date: new Date("2024-12-18T14:00:00"),
        time: "2:00 PM EST",
        importance: "high",
        category: "Fiscal Policy",
        impact: "bullish",
        source: "City Council",
        forecast: "$45M infrastructure spending",
      },
      {
        id: "2",
        title: "Downtown Development Announcement",
        description:
          "Mayor to unveil major mixed-use development project bringing 1,200 residential units and retail space",
        date: new Date("2024-12-19T11:00:00"),
        time: "11:00 AM EST",
        importance: "high",
        category: "Real Estate",
        impact: "bullish",
        source: "Mayor's Office",
        forecast: "$350M investment",
      },
      {
        id: "3",
        title: "Local Employment Report",
        description:
          "Monthly jobs data release covering November employment trends and wage growth statistics",
        date: new Date("2024-12-20T08:30:00"),
        time: "8:30 AM EST",
        importance: "medium",
        category: "Employment",
        impact: "neutral",
        source: "Labor Department",
        previous: "4.1%",
        forecast: "4.0%",
      },
      {
        id: "4",
        title: "Business Tax Incentive Program Launch",
        description:
          "City announces new small business tax credit program to support local entrepreneurship",
        date: new Date("2024-12-21T10:00:00"),
        time: "10:00 AM EST",
        importance: "medium",
        category: "Tax Policy",
        impact: "bullish",
        source: "Economic Development",
        forecast: "$2.5M tax credits",
      },
      {
        id: "5",
        title: "Technology Sector Roundtable",
        description:
          "Quarterly meeting with local tech leaders to discuss growth opportunities and infrastructure needs",
        date: new Date("2024-12-22T15:30:00"),
        time: "3:30 PM EST",
        importance: "medium",
        category: "Technology",
        impact: "bullish",
        source: "Tech Council",
        forecast: "New partnerships",
      },
      {
        id: "6",
        title: "Public Transit Expansion Vote",
        description:
          "City council votes on $120M public transportation improvement initiative",
        date: new Date("2024-12-23T13:00:00"),
        time: "1:00 PM EST",
        importance: "high",
        category: "Infrastructure",
        impact: "bullish",
        source: "Transit Authority",
        forecast: "Expected approval",
      },
      {
        id: "7",
        title: "Housing Affordability Forum",
        description:
          "Community meeting to address rising housing costs and potential policy solutions",
        date: new Date("2025-01-08T18:00:00"),
        time: "6:00 PM EST",
        importance: "medium",
        category: "Housing",
        impact: "neutral",
        source: "Housing Commission",
        forecast: "Policy recommendations",
      },
      {
        id: "8",
        title: "Local Bank Interest Rate Update",
        description:
          "Community bank announces changes to business loan rates and lending criteria",
        date: new Date("2025-01-10T09:00:00"),
        time: "9:00 AM EST",
        importance: "medium",
        category: "Banking",
        impact: "neutral",
        source: "Community Bank",
        previous: "6.25%",
        forecast: "6.00%",
      },
      {
        id: "9",
        title: "Energy Efficiency Grant Awards",
        description:
          "City announces recipients of $3M energy efficiency improvement grants for local businesses",
        date: new Date("2025-01-12T14:00:00"),
        time: "2:00 PM EST",
        importance: "low",
        category: "Energy",
        impact: "bullish",
        source: "Sustainability Office",
        forecast: "25 grants awarded",
      },
      {
        id: "10",
        title: "Quarterly Economic Outlook Presentation",
        description:
          "Chamber of Commerce presents Q1 2025 economic forecast and business confidence survey results",
        date: new Date("2025-01-15T12:00:00"),
        time: "12:00 PM EST",
        importance: "medium",
        category: "Economic Outlook",
        impact: "neutral",
        source: "Chamber of Commerce",
        forecast: "Growth projections",
      },
    ],
    national: [
      {
        id: "1",
        title: "Federal Reserve Interest Rate Decision",
        description:
          "FOMC meeting conclusion with potential rate adjustment and policy statement",
        date: new Date("2024-12-18T14:00:00"),
        time: "2:00 PM EST",
        importance: "high",
        category: "Monetary Policy",
        impact: "neutral",
        source: "Federal Reserve",
        previous: "5.25%",
        forecast: "5.25%",
      },
      {
        id: "2",
        title: "Consumer Price Index Release",
        description:
          "November inflation data showing monthly and annual price changes across all sectors",
        date: new Date("2024-12-19T08:30:00"),
        time: "8:30 AM EST",
        importance: "high",
        category: "Inflation",
        impact: "neutral",
        source: "Bureau of Labor Statistics",
        previous: "3.1%",
        forecast: "3.0%",
      },
      {
        id: "3",
        title: "GDP Final Estimate Q3 2024",
        description:
          "Third and final revision of Q3 economic growth data with detailed sector breakdowns",
        date: new Date("2024-12-20T08:30:00"),
        time: "8:30 AM EST",
        importance: "medium",
        category: "Economic Growth",
        impact: "neutral",
        source: "Bureau of Economic Analysis",
        previous: "2.8%",
        forecast: "2.9%",
      },
      {
        id: "4",
        title: "Employment Situation Report",
        description:
          "December jobs report including unemployment rate, payroll changes, and wage growth",
        date: new Date("2025-01-03T08:30:00"),
        time: "8:30 AM EST",
        importance: "high",
        category: "Employment",
        impact: "neutral",
        source: "Department of Labor",
        previous: "3.7%",
        forecast: "3.7%",
      },
      {
        id: "5",
        title: "Federal Budget Update",
        description:
          "Congressional Budget Office releases updated fiscal year 2025 deficit and spending projections",
        date: new Date("2025-01-07T10:00:00"),
        time: "10:00 AM EST",
        importance: "medium",
        category: "Fiscal Policy",
        impact: "neutral",
        source: "Congressional Budget Office",
        forecast: "$1.8T deficit",
      },
      {
        id: "6",
        title: "Industrial Production Report",
        description:
          "December manufacturing output and capacity utilization data release",
        date: new Date("2025-01-10T09:15:00"),
        time: "9:15 AM EST",
        importance: "medium",
        category: "Manufacturing",
        impact: "neutral",
        source: "Federal Reserve",
        previous: "0.9%",
        forecast: "0.6%",
      },
      {
        id: "7",
        title: "Retail Sales Data",
        description:
          "December consumer spending figures reflecting holiday shopping and economic confidence",
        date: new Date("2025-01-15T08:30:00"),
        time: "8:30 AM EST",
        importance: "medium",
        category: "Consumer Spending",
        impact: "neutral",
        source: "Commerce Department",
        previous: "1.2%",
        forecast: "0.8%",
      },
      {
        id: "8",
        title: "Housing Starts and Permits",
        description:
          "December residential construction data showing building activity and future trends",
        date: new Date("2025-01-17T08:30:00"),
        time: "8:30 AM EST",
        importance: "medium",
        category: "Housing",
        impact: "neutral",
        source: "Census Bureau",
        previous: "6.0%",
        forecast: "3.2%",
      },
      {
        id: "9",
        title: "Producer Price Index",
        description:
          "December wholesale inflation data measuring price pressures in the production pipeline",
        date: new Date("2025-01-21T08:30:00"),
        time: "8:30 AM EST",
        importance: "medium",
        category: "Inflation",
        impact: "neutral",
        source: "Bureau of Labor Statistics",
        previous: "0.8%",
        forecast: "0.5%",
      },
      {
        id: "10",
        title: "Consumer Confidence Survey",
        description:
          "January consumer sentiment data reflecting economic outlook and spending intentions",
        date: new Date("2025-01-28T10:00:00"),
        time: "10:00 AM EST",
        importance: "medium",
        category: "Consumer Sentiment",
        impact: "neutral",
        source: "Conference Board",
        previous: "111.7",
        forecast: "109.5",
      },
    ],
    state: [
      {
        id: "1",
        title: "State Economic Development Summit",
        description:
          "Annual summit featuring major economic development announcements and investment plans",
        date: new Date("2024-12-19T09:00:00"),
        time: "9:00 AM EST",
        importance: "high",
        category: "Development",
        impact: "bullish",
        source: "Economic Development Authority",
        forecast: "Major announcements expected",
      },
      {
        id: "2",
        title: "Governor's Budget Address",
        description:
          "Annual budget presentation outlining fiscal year 2025 spending priorities and revenue projections",
        date: new Date("2025-01-14T13:00:00"),
        time: "1:00 PM EST",
        importance: "high",
        category: "Budget",
        impact: "neutral",
        source: "Governor's Office",
        forecast: "$85B total budget",
      },
      {
        id: "3",
        title: "State Employment Report",
        description:
          "December jobs data covering unemployment rates across all metropolitan areas",
        date: new Date("2025-01-16T09:00:00"),
        time: "9:00 AM EST",
        importance: "medium",
        category: "Employment",
        impact: "neutral",
        source: "Labor Department",
        previous: "3.9%",
        forecast: "3.8%",
      },
      {
        id: "4",
        title: "Infrastructure Investment Plan Unveiling",
        description:
          "Multi-year transportation and broadband infrastructure improvement strategy announcement",
        date: new Date("2025-01-20T10:30:00"),
        time: "10:30 AM EST",
        importance: "high",
        category: "Infrastructure",
        impact: "bullish",
        source: "Transportation Department",
        forecast: "$2.8B investment",
      },
      {
        id: "5",
        title: "Energy Policy Update",
        description:
          "Renewable energy targets revision and utility incentive program modifications",
        date: new Date("2025-01-22T14:00:00"),
        time: "2:00 PM EST",
        importance: "medium",
        category: "Energy",
        impact: "bullish",
        source: "Public Utilities Commission",
        forecast: "Increased targets",
      },
      {
        id: "6",
        title: "Agriculture Export Trade Mission",
        description:
          "State-led international trade mission to promote agricultural products in Asian markets",
        date: new Date("2025-01-25T07:00:00"),
        time: "7:00 AM EST",
        importance: "medium",
        category: "Agriculture",
        impact: "bullish",
        source: "Agriculture Department",
        forecast: "New trade agreements",
      },
      {
        id: "7",
        title: "Education Funding Formula Review",
        description:
          "Legislative committee reviews per-pupil funding formula and resource allocation methods",
        date: new Date("2025-01-27T11:00:00"),
        time: "11:00 AM EST",
        importance: "medium",
        category: "Education",
        impact: "neutral",
        source: "Education Committee",
        forecast: "Formula adjustments",
      },
      {
        id: "8",
        title: "Technology Sector Investment Incentives",
        description:
          "New tax credit program launch targeting technology companies and innovation centers",
        date: new Date("2025-01-29T15:00:00"),
        time: "3:00 PM EST",
        importance: "medium",
        category: "Technology",
        impact: "bullish",
        source: "Innovation Council",
        forecast: "$50M in credits",
      },
      {
        id: "9",
        title: "State Bond Rating Review",
        description:
          "Credit rating agencies conduct annual review of state's fiscal health and debt management",
        date: new Date("2025-02-03T12:00:00"),
        time: "12:00 PM EST",
        importance: "medium",
        category: "Credit Rating",
        impact: "neutral",
        source: "Treasury Department",
        forecast: "Rating maintained",
      },
      {
        id: "10",
        title: "Tourism Industry Conference",
        description:
          "Annual conference highlighting tourism economic impact and marketing strategy updates",
        date: new Date("2025-02-05T09:30:00"),
        time: "9:30 AM EST",
        importance: "low",
        category: "Tourism",
        impact: "neutral",
        source: "Tourism Commission",
        forecast: "Growth strategies",
      },
    ],
    international: [
      {
        id: "1",
        title: "European Central Bank Rate Decision",
        description:
          "ECB monetary policy meeting with potential rate adjustment and economic outlook",
        date: new Date("2024-12-18T08:45:00"),
        time: "8:45 AM EST",
        importance: "high",
        category: "Monetary Policy",
        impact: "neutral",
        source: "European Central Bank",
        previous: "4.00%",
        forecast: "3.75%",
      },
      {
        id: "2",
        title: "China GDP and Economic Data",
        description:
          "Fourth quarter GDP growth, industrial production, and retail sales figures from world's second-largest economy",
        date: new Date("2025-01-17T02:00:00"),
        time: "2:00 AM EST",
        importance: "high",
        category: "Economic Growth",
        impact: "neutral",
        source: "National Bureau of Statistics China",
        previous: "4.8%",
        forecast: "4.5%",
      },
      {
        id: "3",
        title: "Bank of England Interest Rate Decision",
        description:
          "UK central bank monetary policy committee meeting with potential rate changes",
        date: new Date("2025-01-20T07:00:00"),
        time: "7:00 AM EST",
        importance: "high",
        category: "Monetary Policy",
        impact: "neutral",
        source: "Bank of England",
        previous: "5.25%",
        forecast: "5.00%",
      },
      {
        id: "4",
        title: "European Union Inflation Data",
        description:
          "Eurozone December consumer price index showing inflation trends across member countries",
        date: new Date("2025-01-07T05:00:00"),
        time: "5:00 AM EST",
        importance: "medium",
        category: "Inflation",
        impact: "neutral",
        source: "Eurostat",
        previous: "2.4%",
        forecast: "2.2%",
      },
      {
        id: "5",
        title: "Japan Bank Policy Meeting",
        description:
          "Bank of Japan quarterly monetary policy review and economic projections update",
        date: new Date("2025-01-24T21:00:00"),
        time: "9:00 PM EST",
        importance: "medium",
        category: "Monetary Policy",
        impact: "neutral",
        source: "Bank of Japan",
        previous: "-0.1%",
        forecast: "0.0%",
      },
      {
        id: "6",
        title: "OPEC+ Production Meeting",
        description:
          "Oil cartel quarterly meeting to review production quotas and global demand outlook",
        date: new Date("2025-02-01T04:00:00"),
        time: "4:00 AM EST",
        importance: "medium",
        category: "Energy",
        impact: "neutral",
        source: "OPEC+",
        forecast: "Quota adjustments",
      },
      {
        id: "7",
        title: "IMF Global Economic Outlook",
        description:
          "International Monetary Fund updates world economic growth projections and risk assessments",
        date: new Date("2025-01-21T10:00:00"),
        time: "10:00 AM EST",
        importance: "medium",
        category: "Global Outlook",
        impact: "neutral",
        source: "International Monetary Fund",
        forecast: "Downward revisions",
      },
      {
        id: "8",
        title: "G20 Finance Ministers Meeting",
        description:
          "Major economies coordinate fiscal policies and address global economic challenges",
        date: new Date("2025-02-15T04:00:00"),
        time: "4:00 AM EST",
        importance: "medium",
        category: "International Cooperation",
        impact: "neutral",
        source: "G20",
        forecast: "Policy coordination",
      },
      {
        id: "9",
        title: "World Trade Organization Update",
        description:
          "WTO releases global trade volume data and revises international commerce forecasts",
        date: new Date("2025-02-10T06:00:00"),
        time: "6:00 AM EST",
        importance: "medium",
        category: "Global Trade",
        impact: "neutral",
        source: "World Trade Organization",
        previous: "-1.2%",
        forecast: "-0.8%",
      },
      {
        id: "10",
        title: "Emerging Markets Capital Flows Report",
        description:
          "Institute of International Finance tracks investment flows to developing economies",
        date: new Date("2025-02-20T11:00:00"),
        time: "11:00 AM EST",
        importance: "low",
        category: "Capital Flows",
        impact: "neutral",
        source: "Institute of International Finance",
        forecast: "Continued outflows",
      },
    ],
  };
