export interface Notification {
  id: number;
  sender: string;
  subject: string;
  preview: string;
  body: string;
  timestamp: string;
  type: "forecast" | "alert" | "info" | "market" | "system";
  priority: "urgent" | "high" | "normal" | "low";
  read: boolean;
  starred: boolean;
  archived: boolean;
  category: string;
}

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    sender: "Joseph AI System",
    subject: "Revenue Forecast Update - Q3 projections show 15% growth",
    preview:
      "Your Q3 revenue projections have been updated based on recent market data analysis. The forecast shows a promising 15% growth above target...",
    body: `Dear User,

Your Q3 revenue projections have been updated based on recent market data analysis. The forecast shows a promising 15% growth above target.

Key highlights:
• Revenue growth: 15% above Q2 targets
• Market expansion opportunities identified in 3 new segments
• Customer acquisition rate increased by 23%
• Recommended actions: Focus on customer retention programs

This update affects your:
- Business forecast dashboard
- Financial planning modules
- Growth strategy recommendations

Next steps:
1. Review the detailed forecast in your Business Forecast dashboard
2. Consider adjusting your Q4 targets based on this positive trend
3. Schedule a strategy review meeting with your team

Best regards,
Joseph AI`,
    timestamp: "30 minutes ago",
    type: "forecast",
    priority: "high",
    read: false,
    starred: false,
    archived: false,
    category: "Business Intelligence",
  },
  {
    id: 2,
    sender: "Risk Management System",
    subject: "Supply Chain Risk Alert - Immediate attention required",
    preview:
      "A potential supply chain disruption has been detected in your key supplier network. Risk level: High. Recommended immediate review...",
    body: `RISK ALERT - IMMEDIATE ATTENTION REQUIRED

A potential supply chain disruption has been detected in your key supplier network.

Risk Details:
• Risk Level: High
• Affected Suppliers: 3 primary vendors
• Potential Impact: 2-3 week delay in production
• Financial Impact: Estimated $2.5M

Immediate Actions Required:
1. Contact backup suppliers immediately
2. Review current inventory levels
3. Assess customer impact and communication needs
4. Activate contingency plans

This alert was generated based on:
- Real-time supplier monitoring
- Market disruption indicators
- Historical risk patterns

Please access the Risk Management dashboard for detailed analysis and recommended mitigation strategies.

Time is critical - please respond within 4 hours.

Joseph AI Risk Management`,
    timestamp: "2 hours ago",
    type: "alert",
    priority: "urgent",
    read: false,
    starred: true,
    archived: false,
    category: "Risk Management",
  },
  {
    id: 3,
    sender: "Compliance Monitor",
    subject: "Monthly Compliance Report - All systems compliant",
    preview:
      "Your monthly compliance audit has been completed. Status: Fully Compliant. All regulatory requirements met for this period...",
    body: `Monthly Compliance Report - January 2024

Compliance Status: ✅ FULLY COMPLIANT

Summary:
• All 47 regulatory requirements: PASSED
• Financial compliance score: 98.5%
• Data protection compliance: 100%
• Industry standards adherence: 97.2%

Areas of Excellence:
- Financial reporting accuracy
- Data security protocols
- Employee training completion
- Documentation standards

Minor Recommendations:
1. Update policy documentation (due Q2)
2. Schedule annual security audit
3. Review vendor compliance certificates

Detailed report available in Compliance Dashboard.

This automated report was generated by Joseph AI Compliance Monitor.`,
    timestamp: "4 hours ago",
    type: "info",
    priority: "normal",
    read: true,
    starred: false,
    archived: false,
    category: "Compliance",
  },
  {
    id: 4,
    sender: "Market Intelligence",
    subject: "New competitor analysis available - Market position update",
    preview:
      "A new competitor analysis has been completed. Your market position remains strong with opportunities for expansion identified...",
    body: `Market Intelligence Update

New competitor analysis completed for your industry sector.

Key Findings:
• Your market position: #3 in target segment
• Market share: 12.5% (↑2.1% from last quarter)
• Competitive threats: 2 new entrants identified
• Opportunities: 3 underserved market segments

Competitor Insights:
1. Competitor A: Focusing on premium segment
2. Competitor B: Aggressive pricing strategy
3. New Entrant C: Technology-focused approach

Strategic Recommendations:
- Maintain current market position
- Consider pricing strategy review
- Explore technology partnerships
- Monitor new entrant activities

Full analysis available in Market Intelligence dashboard.

Joseph AI Market Analyst`,
    timestamp: "6 hours ago",
    type: "market",
    priority: "normal",
    read: true,
    starred: false,
    archived: false,
    category: "Market Intelligence",
  },
  {
    id: 5,
    sender: "System Administrator",
    subject: "System maintenance completed - All services restored",
    preview:
      "Scheduled system maintenance has been completed successfully. All services are now fully operational with improved performance...",
    body: `System Maintenance Report

Scheduled maintenance completed successfully at 02:00 AM EST.

Maintenance Activities:
• Database optimization: ✅ Complete
• Security updates: ✅ Applied
• Performance enhancements: ✅ Installed
• Backup verification: ✅ Successful

Improvements:
- 25% faster dashboard loading
- Enhanced security protocols
- Improved data synchronization
- Better mobile responsiveness

Downtime: 47 minutes (within planned window)
Next maintenance: March 15, 2024

All systems are fully operational. Thank you for your patience.

Joseph AI System Administrator`,
    timestamp: "1 day ago",
    type: "system",
    priority: "low",
    read: true,
    starred: false,
    archived: false,
    category: "System",
  },
];
